Add support for support account_recovery_setting
lgallard/terraform-aws-cognito-user-pool pull request #32
Opened 2020-12-28 21:48 UTC by lgallard

2020-12-28 22:25 UTC, hyei requested changes
When I add the ` recovery_mechanisms = []` to my module, it does not get rid of Terraform plan showing that it needs to remove an empty account_recovery_setting block, but not clear if this is something that can be resolved in this module.

I was able to verify adding the following block did explicitly set e-mail only in Cognito, and subsequent terraform plans did not detect any more changes. 

`recovery_mechanisms = [
    {
      name     = "verified_email"
      priority = 1
    },
  ]`

2020-12-28 22:25 UTC, hyei commented on main.tf
> +    for_each = lenght(var.recovery_mechanisms) == 0 ? [] : [1]
Should be length, not lenght

2020-12-28 22:25 UTC, hyei commented on README.md
> +  recovery_mechanism = [
Should be recovery_mechanisms, not recovery_mechanism, based on the code

2020-12-29 00:49 UTC, lgallard commented on main.tf
> +    for_each = lenght(var.recovery_mechanisms) == 0 ? [] : [1]
Thanks!  I just write the code, I couldn't test it (maybe in the future I can include an validate stage in Action)

2020-12-29 00:50 UTC, lgallard commented on README.md
> +  recovery_mechanism = [
Fixed!

2020-12-29 00:53 UTC, lgallard commented
@hyei If it's okay for you, I will merge and ship it!

2020-12-29 00:55 UTC, hyei commented
Yes, this solves my issue, thanks!

2020-12-29 12:46 UTC, lgallard commented
This fixes #17 and #32

2020-12-29 12:46 UTC, merged