Support conditional creation
lgallard/terraform-aws-cognito-user-pool pull request #34
Opened 2021-01-20 10:32 UTC by Necromancerx

Update:
* support `create_user_pool` for conditional creation of cognito user pool
* remove `prevent_destroy = true` incase user want to delete their cognito user pool via `create_user_pool = false`
* documentation/example added for `create_user_pool` variable

2021-01-22 16:27 UTC, lgallard commented
@Necromancerx thanks for the PR. Just a comment, Terraform 14 lets you use count inside module blocks. So this change would aim to versions 12 & 13

2021-01-22 16:29 UTC, lgallard requested changes

2021-01-22 16:29 UTC, lgallard commented on README.md
> +  create_user_pool = false
Can `create_user_pool` be renamed to `enabled` ? This is more "standard"

2021-01-23 05:20 UTC, Necromancerx commented on README.md
> +  create_user_pool = false
That ok. I just based that variable on the VPC module https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest#conditional-creation. I'll update it right away.

2021-01-23 05:38 UTC, Necromancerx commented
> @Necromancerx thanks for the PR. Just a comment, Terraform 14 lets you use count inside module blocks. So this change would aim to versions 12 & 13

I didn't know that they already support module blocks on Terraform 14. Thank you!

2021-01-24 10:22 UTC, merged